AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
